server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Twilio配置
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_twilio_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your_twilio_auth_token}
  from-phone: ${TWILIO_FROM_PHONE:+1234567890}

# AWS SES配置
aws:
  access-key: ${AWS_ACCESS_KEY:your_aws_access_key}
  secret-key: ${AWS_SECRET_KEY:your_aws_secret_key}
  region: ${AWS_REGION:us-east-1}
  ses:
    from-email: ${SES_FROM_EMAIL:noreply@fooddelivery.com}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"