version: '3.8'

services:
  # Infrastructure Services
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    volumes:
      - consul_data:/consul/data
    networks:
      - food-delivery-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - food-delivery-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - food-delivery-network

  # Microservices
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=order_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3002
      - KITCHEN_SERVICE_URL=http://kitchen-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
    depends_on:
      - postgres
      - redis
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=restaurant_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  kitchen-service:
    build: ./kitchen-service
    container_name: kitchen-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=kitchen_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ORDER_SERVICE_URL=http://order-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
    depends_on:
      - postgres
      - redis
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=delivery_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ORDER_SERVICE_URL=http://order-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
    depends_on:
      - postgres
      - redis
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  accounting-service:
    build: ./accounting-service
    container_name: accounting-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=accounting_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - ORDER_SERVICE_URL=http://order-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
    depends_on:
      - postgres
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=notification_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
      - consul
    networks:
      - food-delivery-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  consul_data:

networks:
  food-delivery-network:
    driver: bridge