version: '3.8'

services:
  # Infrastructure Services
  consul:
    image: consul:1.15
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - food-delivery-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - food-delivery-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - food-delivery-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - food-delivery-network

  # Application Services
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=api-gateway
      - SERVICE_ID=api-gateway-1
    depends_on:
      - consul
    networks:
      - food-delivery-network

  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=order-service
      - SERVICE_ID=order-service-1
      - REDIS_ADDR=redis:6379
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - consul
      - redis
      - rabbitmq
    networks:
      - food-delivery-network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=restaurant_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=restaurant-service
      - SERVICE_ID=restaurant-service-1
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - consul
      - redis
    networks:
      - food-delivery-network

  kitchen-service:
    build: ./kitchen-service
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=kitchen_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=kitchen-service
      - SERVICE_ID=kitchen-service-1
      - REDIS_ADDR=redis:6379
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - consul
      - redis
      - rabbitmq
    networks:
      - food-delivery-network

  delivery-service:
    build: ./delivery-service
    ports:
      - "8084:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=delivery_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=delivery-service
      - SERVICE_ID=delivery-service-1
      - REDIS_ADDR=redis:6379
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - consul
      - redis
      - rabbitmq
    networks:
      - food-delivery-network

  accounting-service:
    build: ./accounting-service
    ports:
      - "8085:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=accounting_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=accounting-service
      - SERVICE_ID=accounting-service-1
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - consul
      - redis
    networks:
      - food-delivery-network

  notification-service:
    build: ./notification-service
    ports:
      - "8086:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notification_service
      - CONSUL_ADDR=consul:8500
      - SERVICE_ADDR=notification-service
      - SERVICE_ID=notification-service-1
      - REDIS_ADDR=redis:6379
      - RABBITMQ_ADDR=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - consul
      - redis
      - rabbitmq
    networks:
      - food-delivery-network

volumes:
  postgres_data:

networks:
  food-delivery-network:
    driver: bridge