version: '3.8'

services:
  # Consul for service discovery
  consul:
    image: consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      - food-delivery-network

  # PostgreSQL databases
  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  restaurant-db:
    image: postgres:16-alpine
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  kitchen-db:
    image: postgres:16-alpine
    container_name: kitchen-db
    environment:
      POSTGRES_DB: kitchendb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  delivery-db:
    image: postgres:16-alpine
    container_name: delivery-db
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  accounting-db:
    image: postgres:16-alpine
    container_name: accounting-db
    environment:
      POSTGRES_DB: accountingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - accounting-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  notification-db:
    image: postgres:16-alpine
    container_name: notification-db
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  # Microservices
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - consul
    environment:
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      - order-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@order-db:5432/orderdb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
    container_name: restaurant-service
    depends_on:
      - restaurant-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@restaurant-db:5432/restaurantdb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  kitchen-service:
    build:
      context: .
      dockerfile: kitchen-service/Dockerfile
    container_name: kitchen-service
    depends_on:
      - kitchen-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@kitchen-db:5432/kitchendb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  delivery-service:
    build:
      context: .
      dockerfile: delivery-service/Dockerfile
    container_name: delivery-service
    depends_on:
      - delivery-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@delivery-db:5432/deliverydb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  accounting-service:
    build:
      context: .
      dockerfile: accounting-service/Dockerfile
    container_name: accounting-service
    depends_on:
      - accounting-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@accounting-db:5432/accountingdb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      - notification-db
      - consul
    environment:
      DATABASE_URL: postgres://postgres:postgres@notification-db:5432/notificationdb
      CONSUL_URL: http://consul:8500
      RUST_LOG: debug
    networks:
      - food-delivery-network

volumes:
  order-db-data:
  restaurant-db-data:
  kitchen-db-data:
  delivery-db-data:
  accounting-db-data:
  notification-db-data:

networks:
  food-delivery-network:
    driver: bridge